-- =====================================================
-- SISTEMA DE ÓRDENES DE REPARACIÓN - MIGRACIÓN SQL
-- Ejecutar en Supabase SQL Editor
-- =====================================================

-- 1. Tabla de Mecánicos (lista configurable)
CREATE TABLE IF NOT EXISTS mecanicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    nombre TEXT NOT NULL,
    activo BOOLEAN DEFAULT TRUE
);

ALTER TABLE mecanicos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Acceso Total Mecanicos" ON mecanicos;
CREATE POLICY "Acceso Total Mecanicos" ON mecanicos FOR ALL USING (true) WITH CHECK (true);

-- 2. Tabla principal de Órdenes de Reparación
CREATE TABLE IF NOT EXISTS ordenes_reparacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    folio TEXT UNIQUE NOT NULL,
    
    -- Cliente
    cliente_id UUID REFERENCES clientes(id),
    cliente_nombre TEXT NOT NULL,
    cliente_telefono TEXT,
    cliente_email TEXT,
    
    -- Datos de la orden
    tipo_comprobante TEXT CHECK(tipo_comprobante IN ('Factura', 'Remisión')) DEFAULT 'Remisión',
    equipo TEXT NOT NULL,
    marca_modelo TEXT NOT NULL,
    mecanico TEXT NOT NULL,
    observaciones TEXT,
    notas_revision TEXT,
    sucursal TEXT DEFAULT 'Norte',
    
    -- Estatus y fechas
    estatus TEXT CHECK(estatus IN ('PENDIENTE', 'COTIZACION_ENVIADA', 'EN_PROCESO', 'TERMINADA', 'ENTREGADA')) DEFAULT 'PENDIENTE',
    fecha_aceptacion TIMESTAMPTZ,
    fecha_terminacion TIMESTAMPTZ,
    fecha_entrega TIMESTAMPTZ,
    
    -- Auditoría
    usuario_registro TEXT
);

ALTER TABLE ordenes_reparacion ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Acceso Total Ordenes" ON ordenes_reparacion;
CREATE POLICY "Acceso Total Ordenes" ON ordenes_reparacion FOR ALL USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_ordenes_folio ON ordenes_reparacion(folio);
CREATE INDEX IF NOT EXISTS idx_ordenes_estatus ON ordenes_reparacion(estatus);
CREATE INDEX IF NOT EXISTS idx_ordenes_cliente ON ordenes_reparacion(cliente_id);

-- 3. Tabla de Items/Piezas de cada orden
CREATE TABLE IF NOT EXISTS ordenes_reparacion_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    orden_id BIGINT REFERENCES ordenes_reparacion(id) ON DELETE CASCADE,
    producto_id BIGINT REFERENCES productos(id),
    cantidad NUMERIC NOT NULL DEFAULT 1,
    sku TEXT,
    descripcion TEXT,
    precio_unitario NUMERIC DEFAULT 0,
    precio_sin_iva NUMERIC DEFAULT 0,
    precio_con_iva NUMERIC DEFAULT 0
);

ALTER TABLE ordenes_reparacion_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Acceso Total Ordenes Items" ON ordenes_reparacion_items;
CREATE POLICY "Acceso Total Ordenes Items" ON ordenes_reparacion_items FOR ALL USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_ordenes_items_orden ON ordenes_reparacion_items(orden_id);

-- 4. Agregar columna stock_taller a productos
ALTER TABLE productos ADD COLUMN IF NOT EXISTS stock_taller NUMERIC DEFAULT 0;
