-- =====================================================
-- MÓDULO DE PRODUCTOS - SCHEMA SQL
-- Ejecutar en Supabase SQL Editor
-- =====================================================

-- 1. Tabla Principal de Productos
CREATE TABLE IF NOT EXISTS productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Información básica
  nombre TEXT NOT NULL,
  descripcion TEXT,
  categoria TEXT,
  marca TEXT,
  unidad_medida TEXT DEFAULT 'PZA',
  codigo_barras TEXT,
  sku TEXT UNIQUE,
  imagen_url TEXT,
  
  -- Configuración del producto
  es_servicio BOOLEAN DEFAULT FALSE,
  se_vende BOOLEAN DEFAULT TRUE,
  utiliza_stock BOOLEAN DEFAULT TRUE,
  
  -- Stock Sucursal Norte
  stock_norte NUMERIC DEFAULT 0,
  stock_minimo_norte NUMERIC DEFAULT 0,
  stock_apartado_norte NUMERIC DEFAULT 0,
  ubicacion_norte TEXT,
  
  -- Stock Sucursal Sur
  stock_sur NUMERIC DEFAULT 0,
  stock_minimo_sur NUMERIC DEFAULT 0,
  stock_apartado_sur NUMERIC DEFAULT 0,
  ubicacion_sur TEXT,
  
  -- Stock adicional (Matriz)
  stock_matriz NUMERIC DEFAULT 0,
  
  -- Precios
  precio_publico NUMERIC DEFAULT 0,
  precio_venta_2 NUMERIC DEFAULT 0,
  precio_venta_3 NUMERIC DEFAULT 0,
  precio_mercadolibre NUMERIC DEFAULT 0,
  costo NUMERIC DEFAULT 0,
  
  -- Impuestos
  aplica_impuestos BOOLEAN DEFAULT TRUE,
  iva_porcentaje NUMERIC DEFAULT 16,
  ieps_porcentaje NUMERIC DEFAULT 0,
  
  -- SAT
  clave_sat TEXT,
  
  -- Estado
  activo BOOLEAN DEFAULT TRUE
);

-- 2. Movimientos de Stock (Historial Automático)
CREATE TABLE IF NOT EXISTS movimientos_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  producto_id BIGINT REFERENCES productos(id) ON DELETE CASCADE,
  sucursal TEXT NOT NULL, -- 'Norte', 'Sur', 'Matriz'
  tipo TEXT CHECK(tipo IN ('ENTRADA', 'SALIDA', 'AJUSTE', 'TRANSFERENCIA_IN', 'TRANSFERENCIA_OUT')),
  cantidad NUMERIC NOT NULL,
  stock_anterior NUMERIC,
  stock_nuevo NUMERIC,
  referencia TEXT,
  notas TEXT
);

-- 3. Transferencias entre Sucursales
CREATE TABLE IF NOT EXISTS transferencias_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  producto_id BIGINT REFERENCES productos(id) ON DELETE CASCADE,
  sucursal_origen TEXT NOT NULL,
  sucursal_destino TEXT NOT NULL,
  cantidad NUMERIC NOT NULL,
  notas TEXT
);

-- =====================================================
-- RLS POLICIES (Acceso Público para Simplicidad)
-- =====================================================
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimientos_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE transferencias_stock ENABLE ROW LEVEL SECURITY;

-- Eliminar políticas existentes antes de crear (evita error de duplicación)
DROP POLICY IF EXISTS "Acceso Total Productos" ON productos;
DROP POLICY IF EXISTS "Acceso Total Movimientos" ON movimientos_stock;
DROP POLICY IF EXISTS "Acceso Total Transferencias" ON transferencias_stock;

CREATE POLICY "Acceso Total Productos" ON productos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total Movimientos" ON movimientos_stock FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total Transferencias" ON transferencias_stock FOR ALL USING (true) WITH CHECK (true);

-- =====================================================
-- ÍNDICES PARA RENDIMIENTO
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_productos_nombre ON productos(nombre);
CREATE INDEX IF NOT EXISTS idx_productos_sku ON productos(sku);
CREATE INDEX IF NOT EXISTS idx_productos_categoria ON productos(categoria);
CREATE INDEX IF NOT EXISTS idx_productos_clave_sat ON productos(clave_sat);
CREATE INDEX IF NOT EXISTS idx_movimientos_producto ON movimientos_stock(producto_id);
CREATE INDEX IF NOT EXISTS idx_transferencias_producto ON transferencias_stock(producto_id);

-- =====================================================
-- MIGRACIÓN PARA TABLAS EXISTENTES
-- Ejecutar si la tabla ya existe sin las nuevas columnas
-- =====================================================
ALTER TABLE productos ADD COLUMN IF NOT EXISTS es_servicio BOOLEAN DEFAULT FALSE;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS se_vende BOOLEAN DEFAULT TRUE;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS utiliza_stock BOOLEAN DEFAULT TRUE;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS stock_minimo_norte NUMERIC DEFAULT 0;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS stock_apartado_norte NUMERIC DEFAULT 0;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS ubicacion_norte TEXT;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS stock_minimo_sur NUMERIC DEFAULT 0;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS stock_apartado_sur NUMERIC DEFAULT 0;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS ubicacion_sur TEXT;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS precio_venta_2 NUMERIC DEFAULT 0;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS precio_venta_3 NUMERIC DEFAULT 0;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS precio_mercadolibre NUMERIC DEFAULT 0;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS costo NUMERIC DEFAULT 0;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS aplica_impuestos BOOLEAN DEFAULT TRUE;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS iva_porcentaje NUMERIC DEFAULT 16;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS ieps_porcentaje NUMERIC DEFAULT 0;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS clave_sat TEXT;

-- Migrar stock_minimo existente a stock_minimo_norte si existe
-- UPDATE productos SET stock_minimo_norte = stock_minimo WHERE stock_minimo_norte = 0;
-- Migrar precio_jardinero a precio_venta_2 si existe
-- UPDATE productos SET precio_venta_2 = precio_jardinero WHERE precio_venta_2 = 0;
