-- ==========================================
-- SCRIPT DE MIGRACIÓN: PROVEEDORES Y COMPRAS
-- ==========================================

-- Limpieza de tabla fallida anterior
DROP TABLE IF EXISTS compras_items CASCADE;

-- 1. Tabla de Proveedores (Para el nuevo catálogo)
-- Nota: Para proveedores usamos un BIGINT secuencial tradicional
CREATE TABLE IF NOT EXISTS proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    telefono TEXT,
    rfc TEXT,
    regimen_fiscal TEXT,
    direccion TEXT,
    codigo_postal TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS en proveedores
ALTER TABLE proveedores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir select a todos en proveedores" ON proveedores FOR SELECT USING (true);
CREATE POLICY "Permitir insert a todos en proveedores" ON proveedores FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir update a todos en proveedores" ON proveedores FOR UPDATE USING (true);
CREATE POLICY "Permitir delete a todos en proveedores" ON proveedores FOR DELETE USING (true);

-- 2. Modificar tabla de Gastos
-- NOTA: La tabla gastos ya existe. Su llave primaria es de tipo UUID.
-- Agregamos la columna proveedor_id que será opcional, de tipo BIGINT para enlazarse a proveedores.
ALTER TABLE gastos ADD COLUMN IF NOT EXISTS proveedor_id BIGINT;

-- 3. Tabla de Detalles de Compras (Items para registro de mercancía)
-- gasto_id DEBE ser UUID porque gastos.id es UUID (gen_random_uuid())
CREATE TABLE compras_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gasto_id UUID NOT NULL,
    producto_id BIGINT,
    sku TEXT,
    descripcion TEXT,
    cantidad NUMERIC NOT NULL DEFAULT 1,
    costo_unitario NUMERIC NOT NULL DEFAULT 0.00,
    total NUMERIC NOT NULL DEFAULT 0.00,
    sucursal_destino TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS en compras_items
ALTER TABLE compras_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir select a todos en compras_items" ON compras_items FOR SELECT USING (true);
CREATE POLICY "Permitir insert a todos en compras_items" ON compras_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir update a todos en compras_items" ON compras_items FOR UPDATE USING (true);
CREATE POLICY "Permitir delete a todos en compras_items" ON compras_items FOR DELETE USING (true);

-- 4. Creación de Foreign Keys explícitos al final para evitar interrupciones de DDl
ALTER TABLE gastos ADD CONSTRAINT fk_gastos_proveedor 
    FOREIGN KEY (proveedor_id) REFERENCES proveedores(id) ON DELETE SET NULL;

ALTER TABLE compras_items ADD CONSTRAINT fk_compras_items_gasto 
    FOREIGN KEY (gasto_id) REFERENCES gastos(id) ON DELETE CASCADE;

ALTER TABLE compras_items ADD CONSTRAINT fk_compras_items_producto 
    FOREIGN KEY (producto_id) REFERENCES productos(id) ON DELETE SET NULL;

-- 5. Creación de índices
CREATE INDEX IF NOT EXISTS idx_compras_items_gasto_id ON compras_items(gasto_id);
CREATE INDEX IF NOT EXISTS idx_compras_items_producto_id ON compras_items(producto_id);
CREATE INDEX IF NOT EXISTS idx_gastos_proveedor_id ON gastos(proveedor_id);
