-- =====================================================
-- AGRIGARDEN - SCHEMA COMPLETO PARA AMBIENTE TEST
-- Ejecutar en: Supabase SQL Editor (Proyecto Agrigarden-Test)
-- =====================================================
-- Este script crea todas las tablas necesarias para el ambiente de pruebas.
-- Generado automáticamente desde producción.
-- =====================================================

-- 1. BITÁCORA DE COBRANZA
CREATE TABLE IF NOT EXISTS bitacora_cobranza (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  fecha_promesa DATE,
  transaccion_id BIGINT,
  nota TEXT
);

-- 2. BITÁCORA DE PROVEEDORES
CREATE TABLE IF NOT EXISTS bitacora_proveedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nota TEXT,
  gasto_id UUID
);

-- 3. CAJA MOVIMIENTOS (POS)
CREATE TABLE IF NOT EXISTS caja_movimientos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  sesion_id BIGINT,
  tipo TEXT,
  monto NUMERIC,
  concepto TEXT,
  usuario TEXT
);

-- 4. CAJA SESIONES (POS)
CREATE TABLE IF NOT EXISTS caja_sesiones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  sucursal TEXT,
  fecha DATE,
  fecha_apertura TIMESTAMPTZ,
  fondo_inicial NUMERIC DEFAULT 0,
  usuario_apertura TEXT,
  fecha_cierre TIMESTAMPTZ,
  efectivo_esperado NUMERIC,
  efectivo_real NUMERIC,
  diferencia NUMERIC,
  fondo_siguiente NUMERIC,
  retiro_banco NUMERIC,
  usuario_cierre TEXT,
  notas_cierre TEXT,
  estado TEXT DEFAULT 'ABIERTA'
);

-- 5. COMPRAS AGRIGARDEN
CREATE TABLE IF NOT EXISTS compras_agrigarden (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  fecha_creacion DATE,
  fecha_orden DATE,
  fecha_tentativa_recepcion DATE,
  numero_orden TEXT,
  proveedor TEXT,
  solicitante TEXT DEFAULT 'Administrador',
  nombre_solicitante TEXT,
  sucursal_origen TEXT,
  total_monto NUMERIC DEFAULT 0.00,
  estado TEXT DEFAULT 'Pendiente',
  notas_internas TEXT,
  url_cotizacion TEXT
);

-- 6. COMPRAS ITEMS
CREATE TABLE IF NOT EXISTS compras_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  compra_id UUID,
  codigo_producto TEXT,
  nombre_producto TEXT,
  cantidad INTEGER DEFAULT 1,
  precio_unitario NUMERIC DEFAULT 0.00,
  costo_total NUMERIC
);

-- 7. EMPLEADOS
CREATE TABLE IF NOT EXISTS empleados (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nombre_completo TEXT,
  fecha_nacimiento DATE,
  edad INTEGER,
  fecha_ingreso DATE,
  puesto TEXT,
  sucursal TEXT,
  reporta_a UUID,
  tipo_contrato TEXT,
  duracion_contrato TEXT,
  sueldo_base NUMERIC DEFAULT 1200,
  banco TEXT,
  cuenta_banco TEXT,
  telefono TEXT,
  correo_electronico TEXT,
  nss TEXT,
  rfc TEXT,
  curp TEXT,
  estado_civil TEXT,
  direccion_completa TEXT,
  escolaridad TEXT,
  prestaciones TEXT[],
  foto_url TEXT,
  estatus TEXT DEFAULT 'Activo',
  motivo_baja TEXT
);

-- 8. ESTADOS RESULTADOS
CREATE TABLE IF NOT EXISTS estados_resultados (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  anio INTEGER,
  mes INTEGER,
  sucursal TEXT,
  ingresos_ventas NUMERIC DEFAULT 0,
  ingresos_servicios NUMERIC DEFAULT 0,
  total_ingresos NUMERIC DEFAULT 0,
  costo_ventas NUMERIC DEFAULT 0,
  utilidad_bruta NUMERIC DEFAULT 0,
  gastos_operacion NUMERIC DEFAULT 0,
  utilidad_operacion NUMERIC DEFAULT 0,
  gastos_financieros NUMERIC DEFAULT 0,
  gastos_contables NUMERIC DEFAULT 0,
  utilidad_neta NUMERIC DEFAULT 0,
  cerrado BOOLEAN DEFAULT TRUE
);

-- 9. FLOTILLA VEHÍCULOS
CREATE TABLE IF NOT EXISTS flotilla_vehiculos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  marca TEXT,
  modelo TEXT,
  anio INTEGER,
  placas TEXT,
  responsable TEXT,
  ultimo_mantenimiento DATE,
  ultimo_cambio_aceite DATE,
  proximo_cambio_aceite DATE,
  ultima_verificacion DATE,
  ultimo_pago_seguro DATE,
  tenencia_pagada BOOLEAN DEFAULT FALSE,
  se_hizo_cambio_placas BOOLEAN DEFAULT FALSE
);

-- 10. GASTOS
CREATE TABLE IF NOT EXISTS gastos (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  proveedor TEXT,
  categoria TEXT,
  subcategoria TEXT,
  sucursal TEXT,
  monto_total NUMERIC,
  metodo_pago TEXT,
  estado_pago TEXT,
  dias_credito NUMERIC,
  fecha_limite_pago DATE,
  saldo_pendiente NUMERIC,
  notas TEXT
);

-- 11. INVENTARIO MENSUAL
CREATE TABLE IF NOT EXISTS inventario_mensual (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  mes INTEGER,
  anio INTEGER,
  sucursal TEXT DEFAULT 'Matriz',
  monto_inicial NUMERIC DEFAULT 0,
  monto_final NUMERIC DEFAULT 0
);

-- 12. INVERSIONES
CREATE TABLE IF NOT EXISTS inversiones (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  fecha_adquisicion DATE,
  descripcion TEXT,
  categoria TEXT,
  tipo_inversion TEXT,
  monto NUMERIC,
  vida_util INTEGER,
  tasa_interes NUMERIC DEFAULT 0,
  plazo_meses INTEGER DEFAULT 0,
  pago_mensual NUMERIC DEFAULT 0,
  proveedor TEXT,
  sucursal TEXT DEFAULT 'Matriz',
  estatus TEXT DEFAULT 'Activo',
  notas TEXT
);

-- 13. LISTA PROVEEDORES
CREATE TABLE IF NOT EXISTS lista_proveedores (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nombre TEXT
);

-- 14. MOVIMIENTOS STOCK
CREATE TABLE IF NOT EXISTS movimientos_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  producto_id BIGINT,
  sucursal TEXT,
  tipo TEXT,
  cantidad NUMERIC,
  stock_anterior NUMERIC,
  stock_nuevo NUMERIC,
  referencia TEXT,
  notas TEXT
);

-- 15. PRÉSTAMOS
CREATE TABLE IF NOT EXISTS prestamos (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  prestamista TEXT,
  fecha_obtencion DATE,
  capital NUMERIC,
  tasa_anual NUMERIC,
  plazo INTEGER,
  periodicidad TEXT,
  mensualidad NUMERIC,
  descripcion TEXT,
  sucursal TEXT,
  estatus TEXT DEFAULT 'Activo',
  notas TEXT
);

-- 16. PRODUCTOS
CREATE TABLE IF NOT EXISTS productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nombre TEXT,
  descripcion TEXT,
  categoria TEXT,
  marca TEXT,
  unidad_medida TEXT DEFAULT 'PZA',
  codigo_barras TEXT,
  sku TEXT,
  imagen_url TEXT,
  es_servicio BOOLEAN DEFAULT FALSE,
  se_vende BOOLEAN DEFAULT TRUE,
  utiliza_stock BOOLEAN DEFAULT TRUE,
  stock_norte NUMERIC DEFAULT 0,
  stock_minimo_norte NUMERIC DEFAULT 0,
  stock_apartado_norte NUMERIC DEFAULT 0,
  ubicacion_norte TEXT,
  stock_sur NUMERIC DEFAULT 0,
  stock_minimo_sur NUMERIC DEFAULT 0,
  stock_apartado_sur NUMERIC DEFAULT 0,
  ubicacion_sur TEXT,
  stock_matriz NUMERIC DEFAULT 0,
  stock_minimo NUMERIC DEFAULT 0,
  precio_publico NUMERIC DEFAULT 0,
  precio_jardinero NUMERIC DEFAULT 0,
  precio_venta_2 NUMERIC DEFAULT 0,
  precio_venta_3 NUMERIC DEFAULT 0,
  precio_mercadolibre NUMERIC DEFAULT 0,
  costo NUMERIC DEFAULT 0,
  aplica_impuestos BOOLEAN DEFAULT TRUE,
  iva_porcentaje NUMERIC DEFAULT 16,
  ieps_porcentaje NUMERIC DEFAULT 0,
  clave_sat TEXT,
  activo BOOLEAN DEFAULT TRUE
);

-- 17. RRHH HISTORIAL PUESTOS
CREATE TABLE IF NOT EXISTS rrhh_historial_puestos (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  empleado_id UUID,
  fecha_cambio DATE DEFAULT CURRENT_DATE,
  puesto_anterior TEXT,
  puesto_nuevo TEXT,
  motivo TEXT
);

-- 18. RRHH NÓMINA
CREATE TABLE IF NOT EXISTS rrhh_nomina (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  empleado_id UUID,
  periodo DATE,
  periodo_inicio DATE,
  periodo_fin DATE,
  sueldo_base NUMERIC,
  bonificaciones NUMERIC DEFAULT 0,
  deducciones NUMERIC DEFAULT 0,
  total_neto NUMERIC,
  metodo_pago TEXT,
  fecha_pago TIMESTAMPTZ,
  estado TEXT DEFAULT 'Pendiente'
);

-- 19. RRHH TAREA BITÁCORA
CREATE TABLE IF NOT EXISTS rrhh_tarea_bitacora (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  tarea_id UUID,
  tipo TEXT DEFAULT 'Comentario',
  nota TEXT,
  usuario TEXT
);

-- 20. RRHH TAREAS
CREATE TABLE IF NOT EXISTS rrhh_tareas (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  empleado_id UUID,
  titulo TEXT,
  descripcion TEXT,
  categoria TEXT,
  prioridad TEXT DEFAULT 'Media',
  estado TEXT DEFAULT 'PENDIENTE',
  fecha_vencimiento DATE,
  referencia_folio TEXT
);

-- 21. RRHH VACACIONES
CREATE TABLE IF NOT EXISTS rrhh_vacaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  empleado_id UUID,
  fecha_inicio DATE,
  fecha_fin DATE,
  dias_tomados INTEGER,
  comentarios TEXT
);

-- 22. RRHH VISTA ANALYTICS (Vista materializada como tabla simple)
CREATE TABLE IF NOT EXISTS rrhh_vista_analytics (
  sucursal TEXT,
  puesto TEXT,
  headcount_total BIGINT,
  promedio_antiguedad NUMERIC
);

-- 23. SYS CONFIG
CREATE TABLE IF NOT EXISTS sys_config (
  key TEXT PRIMARY KEY,
  value JSONB,
  description TEXT
);

-- 24. SYS METAS INGRESOS
CREATE TABLE IF NOT EXISTS sys_metas_ingresos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anio INTEGER,
  mes INTEGER,
  sucursal TEXT DEFAULT 'Norte',
  monto_meta NUMERIC DEFAULT 0
);

-- 25. SYS USUARIOS
CREATE TABLE IF NOT EXISTS sys_usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  nombre TEXT,
  email TEXT,
  password TEXT,
  rol TEXT DEFAULT 'admin'
);

-- 26. TRANSACCIONES
CREATE TABLE IF NOT EXISTS transacciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  tipo TEXT,
  sucursal TEXT,
  monto DOUBLE PRECISION,
  metodo_pago TEXT,
  comision_bancaria DOUBLE PRECISION,
  monto_neto DOUBLE PRECISION,
  categoria TEXT,
  nombre_cliente TEXT,
  telefono_cliente TEXT,
  estado_cobro TEXT,
  saldo_pendiente NUMERIC,
  nivel_cobranza INTEGER DEFAULT 0,
  ultimo_whatsapp TIMESTAMPTZ,
  proximo_whatsapp TIMESTAMPTZ,
  nota TEXT,
  notas TEXT
);

-- 27. TRANSFERENCIAS STOCK
CREATE TABLE IF NOT EXISTS transferencias_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  producto_id BIGINT,
  sucursal_origen TEXT,
  sucursal_destino TEXT,
  cantidad NUMERIC,
  notas TEXT
);

-- 28. VENTA ITEMS
CREATE TABLE IF NOT EXISTS venta_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  transaccion_id UUID,
  sesion_caja_id BIGINT,
  producto_id BIGINT,
  producto_nombre TEXT,
  producto_sku TEXT,
  cantidad NUMERIC,
  precio_unitario NUMERIC,
  precio_tipo TEXT,
  descuento_porcentaje NUMERIC DEFAULT 0,
  subtotal NUMERIC,
  iva_porcentaje NUMERIC DEFAULT 0,
  iva_monto NUMERIC DEFAULT 0,
  ieps_porcentaje NUMERIC DEFAULT 0,
  ieps_monto NUMERIC DEFAULT 0,
  total NUMERIC
);

-- =====================================================
-- HABILITAR RLS Y CREAR POLÍTICAS DE ACCESO PÚBLICO
-- =====================================================

ALTER TABLE bitacora_cobranza ENABLE ROW LEVEL SECURITY;
ALTER TABLE bitacora_proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE caja_movimientos ENABLE ROW LEVEL SECURITY;
ALTER TABLE caja_sesiones ENABLE ROW LEVEL SECURITY;
ALTER TABLE compras_agrigarden ENABLE ROW LEVEL SECURITY;
ALTER TABLE compras_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE empleados ENABLE ROW LEVEL SECURITY;
ALTER TABLE estados_resultados ENABLE ROW LEVEL SECURITY;
ALTER TABLE flotilla_vehiculos ENABLE ROW LEVEL SECURITY;
ALTER TABLE gastos ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventario_mensual ENABLE ROW LEVEL SECURITY;
ALTER TABLE inversiones ENABLE ROW LEVEL SECURITY;
ALTER TABLE lista_proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimientos_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE prestamos ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE rrhh_historial_puestos ENABLE ROW LEVEL SECURITY;
ALTER TABLE rrhh_nomina ENABLE ROW LEVEL SECURITY;
ALTER TABLE rrhh_tarea_bitacora ENABLE ROW LEVEL SECURITY;
ALTER TABLE rrhh_tareas ENABLE ROW LEVEL SECURITY;
ALTER TABLE rrhh_vacaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE rrhh_vista_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE sys_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE sys_metas_ingresos ENABLE ROW LEVEL SECURITY;
ALTER TABLE sys_usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE transacciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE transferencias_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE venta_items ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso público (igual que producción)
CREATE POLICY "Acceso Total" ON bitacora_cobranza FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON bitacora_proveedores FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON caja_movimientos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON caja_sesiones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON compras_agrigarden FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON compras_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON empleados FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON estados_resultados FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON flotilla_vehiculos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON gastos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON inventario_mensual FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON inversiones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON lista_proveedores FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON movimientos_stock FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON prestamos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON productos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON rrhh_historial_puestos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON rrhh_nomina FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON rrhh_tarea_bitacora FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON rrhh_tareas FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON rrhh_vacaciones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON rrhh_vista_analytics FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON sys_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON sys_metas_ingresos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON sys_usuarios FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON transacciones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON transferencias_stock FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total" ON venta_items FOR ALL USING (true) WITH CHECK (true);

-- =====================================================
-- DATOS INICIALES (Para que funcione la app)
-- =====================================================

-- Usuario Admin por defecto
INSERT INTO sys_usuarios (nombre, email, password)
VALUES ('Administrador', 'admin@agrigarden.com', 'Maestro2024*')
ON CONFLICT DO NOTHING;

-- Configuración de comisiones
INSERT INTO sys_config (key, value, description)
VALUES (
  'tasas_comision',
  '{"Efectivo": 0, "Transferencia": 0, "Tarjeta Mercado Pago": 0.035, "Tarjeta Hey Banco": 0.021, "Tarjeta BBVA": 0.025, "Cheque": 0, "Otro": 0, "Crédito": 0}'::jsonb,
  'Tasas de comisión por método de pago'
) ON CONFLICT (key) DO NOTHING;

-- Meta mensual inicial
INSERT INTO sys_metas_ingresos (anio, mes, sucursal, monto_meta)
VALUES 
  (2026, 1, 'Norte', 300000),
  (2026, 1, 'Sur', 300000)
ON CONFLICT DO NOTHING;

-- =====================================================
-- ¡LISTO! El schema está completo.
-- =====================================================
