-- Creación de la tabla de Inventario Mensual
create table public.inventario_mensual (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  mes integer not null check (mes >= 1 and mes <= 12),
  anio integer not null,
  monto_inicial numeric default 0,
  monto_final numeric default 0,
  
  -- Evitar duplicados para el mismo mes y año
  constraint inventario_mensual_mes_anio_key unique (mes, anio)
);

-- Habilitar RLS (Recomendado)
alter table public.inventario_mensual enable row level security;

-- Política de acceso total (para simplificar, ajusta según necesidad)
create policy "Acceso total a inventario"
on public.inventario_mensual
for all
using (true)
with check (true);

-- CONTROL DE FLOTILLAS
create table public.flotilla_vehiculos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  marca text not null,
  modelo text not null,
  anio integer not null,
  placas text not null,
  responsable text, 
  ultimo_mantenimiento date,
  ultimo_cambio_aceite date,
  proximo_cambio_aceite date, 
  ultima_verificacion date,
  ultimo_pago_seguro date,
  tenencia_pagada boolean default false,
  se_hizo_cambio_placas boolean default false
);

alter table public.flotilla_vehiculos enable row level security;
create policy "Acceso Total Flotilla" on public.flotilla_vehiculos for all using (true) with check (true);

-- MODULO DE CONFIGURACION (SISTEMA)

-- 1. Tabla de Usuarios (Auth propio simple)
create table public.sys_usuarios (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text not null,
  email text not null unique,
  password text not null, -- Texto plano por simplicidad segun requerimiento
  rol text default 'admin'
);
alter table public.sys_usuarios enable row level security;
create policy "Acceso Publico Usuarios" on public.sys_usuarios for all using (true) with check (true);

-- Usuario Admin por defecto
insert into public.sys_usuarios (nombre, email, password)
values ('Administrador', 'admin@agrigarden.com', 'Maestro2024*')
on conflict (email) do nothing;

-- 2. Tabla de Configuración Global (Key-Value)
create table public.sys_config (
  key text primary key,
  value jsonb not null,
  description text
);
alter table public.sys_config enable row level security;
create policy "Acceso Publico Config" on public.sys_config for all using (true) with check (true);

-- Configuración inicial: Comisiones
insert into public.sys_config (key, value, description)
values (
  'tasas_comision',
  '{
    "Efectivo": 0,
    "Transferencia": 0,
    "Tarjeta Mercado Pago": 0.035,
    "Tarjeta Hey Banco": 0.021,
    "Tarjeta BBVA": 0.025,
    "Cheque": 0,
    "Otro": 0,
    "Crédito": 0
  }'::jsonb,
  'Tasas de comisión por método de pago'
) on conflict (key) do nothing;

-- 3. Tabla de Metas de Ingresos Mensuales
create table public.sys_metas_ingresos (
  id bigint generated by default as identity primary key,
  anio integer not null,
  mes integer not null check (mes >= 1 and mes <= 12),
  monto_meta numeric not null default 0,
  constraint sys_metas_unique unique (anio, mes)
);
alter table public.sys_metas_ingresos enable row level security;
create policy "Acceso Publico Metas" on public.sys_metas_ingresos for all using (true) with check (true);

-- Meta inicial global (se usará como fallback o registro inicial)
insert into public.sys_metas_ingresos (anio, mes, monto_meta)
values (extract(year from now())::int, extract(month from now())::int, 300000)
on conflict do nothing;

