-- =====================================================
-- FIX: CORRECCIÓN DE TIPO DE DATO EN VENTA_ITEMS
-- Ejecutar en Supabase SQL Editor
-- =====================================================

-- 1. Eliminar la tabla venta_items (ya que actualmente está vacía y tiene el tipo incorrecto)
DROP TABLE IF EXISTS venta_items;

-- 2. Recrear la tabla con transaccion_id como BIGINT para que coincida con transacciones.id
CREATE TABLE IF NOT EXISTS venta_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  transaccion_id BIGINT NOT NULL,       -- Referencia a transacciones.id (Corregido de UUID a BIGINT)
  sesion_caja_id BIGINT REFERENCES caja_sesiones(id),

  producto_id BIGINT REFERENCES productos(id),
  producto_nombre TEXT,
  producto_sku TEXT,

  cantidad NUMERIC(10,2) NOT NULL,
  precio_unitario NUMERIC(12,2) NOT NULL,
  precio_tipo TEXT,

  descuento_porcentaje NUMERIC(5,2) DEFAULT 0,
  subtotal NUMERIC(12,2),

  iva_porcentaje NUMERIC(5,2) DEFAULT 0,
  iva_monto NUMERIC(12,2) DEFAULT 0,
  ieps_porcentaje NUMERIC(5,2) DEFAULT 0,
  ieps_monto NUMERIC(12,2) DEFAULT 0,

  total NUMERIC(12,2)
);

-- 3. Habilitar RLS y recrear políticas
ALTER TABLE venta_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Acceso Total Venta Items" ON venta_items;
CREATE POLICY "Acceso Total Venta Items" ON venta_items FOR ALL USING (true) WITH CHECK (true);

-- 4. Recrear índices
CREATE INDEX IF NOT EXISTS idx_venta_items_transaccion ON venta_items(transaccion_id);
CREATE INDEX IF NOT EXISTS idx_venta_items_sesion ON venta_items(sesion_caja_id);
CREATE INDEX IF NOT EXISTS idx_venta_items_producto ON venta_items(producto_id);
CREATE INDEX IF NOT EXISTS idx_venta_items_fecha ON venta_items(created_at);

-- FIN DEL SCRIPT
