-- SCRIPT DE ACTUALIZACIÓN FLOTILLAS
-- Ejecutar en el SQL Editor de Supabase

-- 1. Añadir campos básicos a la tabla principal
ALTER TABLE public.flotilla_vehiculos ADD COLUMN IF NOT EXISTS numero_serie TEXT;
ALTER TABLE public.flotilla_vehiculos ADD COLUMN IF NOT EXISTS kilometraje_actual INTEGER DEFAULT 0;

-- 2. Tabla para Bitácora de Fallas
CREATE TABLE IF NOT EXISTS public.flotilla_bitacora_fallas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehiculo_id BIGINT REFERENCES public.flotilla_vehiculos(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    fecha DATE DEFAULT CURRENT_DATE,
    descripcion TEXT NOT NULL,
    estatus TEXT DEFAULT 'Reportada' -- Reportada, Reparada, Descartada
);

-- 3. Tabla para Historial de Kilometraje
CREATE TABLE IF NOT EXISTS public.flotilla_bitacora_kilometraje (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehiculo_id BIGINT REFERENCES public.flotilla_vehiculos(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    fecha DATE DEFAULT CURRENT_DATE,
    kilometraje INTEGER NOT NULL,
    nota TEXT
);

-- 4. Habilitar Seguridad (RLS)
ALTER TABLE public.flotilla_bitacora_fallas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.flotilla_bitacora_kilometraje ENABLE ROW LEVEL SECURITY;

-- Políticas (Permitir todo para simplificar según arquitectura actual)
DROP POLICY IF EXISTS "Acceso Total Fallas" ON public.flotilla_bitacora_fallas;
CREATE POLICY "Acceso Total Fallas" ON public.flotilla_bitacora_fallas FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso Total Kilometraje" ON public.flotilla_bitacora_kilometraje;
CREATE POLICY "Acceso Total Kilometraje" ON public.flotilla_bitacora_kilometraje FOR ALL USING (true) WITH CHECK (true);
