-- SQL SCRIPT FOR AGRIGARDEN POS VENDEDORES REFACTOR
-- Run this in the Supabase SQL Editor

-- 1. Crear tabla para vendedores
CREATE TABLE IF NOT EXISTS public.sys_vendedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Asegurarnos que existan las columnas para registrar al vendedor (opcional)
-- en transacciones y venta_items
ALTER TABLE public.transacciones ADD COLUMN IF NOT EXISTS vendedor_nombre TEXT;
ALTER TABLE public.venta_items ADD COLUMN IF NOT EXISTS vendedor_nombre TEXT;

-- 3. Habilitar RLS (Row Level Security) y crear política de lectura/escritura abierta
-- Como este es el sistema interno, la política anon se queda por ahora abierta.
ALTER TABLE public.sys_vendedores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acceso total a sys_vendedores" 
ON public.sys_vendedores 
FOR ALL USING (true) WITH CHECK (true);

-- Insertar un vendedor default para pruebas iniciales
INSERT INTO public.sys_vendedores (nombre, activo) 
VALUES ('Mostrador Principal', true);
