-- 1. Actualizar tabla de vehiculos para soportar modalidad de 1 o 2 personas
ALTER TABLE flotilla_vehiculos
ADD COLUMN IF NOT EXISTS tipo_asignacion INT DEFAULT 1,
ADD COLUMN IF NOT EXISTS responsable1 TEXT,
ADD COLUMN IF NOT EXISTS responsable2 TEXT;

-- Migración básica: transferir `responsable` actual a `responsable1` en caso de que no lo tengan.
UPDATE flotilla_vehiculos 
SET responsable1 = responsable 
WHERE responsable1 IS NULL AND responsable IS NOT NULL;

-- 2. Crear tabla de cargas de combustible
CREATE TABLE IF NOT EXISTS flotilla_cargas_combustible (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehiculo_id BIGINT REFERENCES flotilla_vehiculos(id) ON DELETE CASCADE,
    responsable TEXT,
    fecha DATE NOT NULL,
    kilometraje NUMERIC NOT NULL,
    monto NUMERIC NOT NULL,
    precio_litro NUMERIC NOT NULL,
    metodo_pago TEXT NOT NULL,
    sucursal TEXT NOT NULL,
    gasto_id UUID, -- Referencia opcional al uuid generado en la tabla gastos
    rendimiento_kml NUMERIC, -- km/l calculado (distancia / litros)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Crear tabla de bitácora de uso para vehículos compartidos (2 personas)
CREATE TABLE IF NOT EXISTS flotilla_bitacora_uso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehiculo_id BIGINT REFERENCES flotilla_vehiculos(id) ON DELETE CASCADE,
    responsable TEXT NOT NULL,
    fecha_hora_salida TIMESTAMP WITH TIME ZONE NOT NULL,
    km_salida NUMERIC NOT NULL,
    fecha_hora_regreso TIMESTAMP WITH TIME ZONE,
    km_regreso NUMERIC,
    carga_combustible_id BIGINT REFERENCES flotilla_cargas_combustible(id) ON DELETE SET NULL, -- Si cargó al entregar
    km_recorridos NUMERIC GENERATED ALWAYS AS (km_regreso - km_salida) STORED,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS (Row Level Security) - Dejarlo desactivado para simplificar si el sistema no lo requiere, 
-- pero aquí lo creamos por si acaso
-- ALTER TABLE flotilla_cargas_combustible ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE flotilla_bitacora_uso ENABLE ROW LEVEL SECURITY;
