-- Migration for RRHH Extended Features

-- 1. Add reason for termination to employees
ALTER TABLE empleados ADD COLUMN IF NOT EXISTS motivo_baja text DEFAULT null;

-- 2. Create Vacations Tracking Table
CREATE TABLE IF NOT EXISTS rrhh_vacaciones (
    id bigint generated by default as identity primary key,
    empleado_id uuid references empleados(id) ON DELETE CASCADE,
    fecha_inicio date not null,
    fecha_fin date not null,
    dias_tomados integer not null, -- Can be negative strictly speaking if we wanted to credit days, but typically positive. Adjust logic in JS.
    comentarios text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Add RLS Policies for Vacations (Public for now as per project standard)
ALTER TABLE rrhh_vacaciones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Select Vacaciones" ON rrhh_vacaciones;
CREATE POLICY "Public Select Vacaciones" ON rrhh_vacaciones FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Insert Vacaciones" ON rrhh_vacaciones;
CREATE POLICY "Public Insert Vacaciones" ON rrhh_vacaciones FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Update Vacaciones" ON rrhh_vacaciones;
CREATE POLICY "Public Update Vacaciones" ON rrhh_vacaciones FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public Delete Vacaciones" ON rrhh_vacaciones;
CREATE POLICY "Public Delete Vacaciones" ON rrhh_vacaciones FOR DELETE USING (true);
