-- =====================================================
-- NUEVA TABLA: sys_metodos_pago
-- Métodos de pago dinámicos con comisiones
-- Ejecutar en Supabase SQL Editor
-- =====================================================

-- 1. Crear la tabla
CREATE TABLE IF NOT EXISTS sys_metodos_pago (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMPTZ DEFAULT NOW(),

    nombre      TEXT NOT NULL UNIQUE,          -- Nombre visible del método
    tasa_base   NUMERIC(6,4) DEFAULT 0,        -- Comisión en decimal (ej. 0.03 = 3%)
    aplica_iva  BOOLEAN DEFAULT TRUE,          -- Si la comisión lleva IVA (16%)
    activo      BOOLEAN DEFAULT TRUE,          -- Si aparece en los selectores
    orden       INTEGER DEFAULT 99             -- Orden de aparición en pantallas
);

-- 2. Poblar con los métodos actuales del sistema
-- (Las tasas están en 0 — configúralas en el módulo de Configuración)
INSERT INTO sys_metodos_pago (nombre, tasa_base, aplica_iva, activo, orden) VALUES
    ('Efectivo',                              0,      FALSE, TRUE,  1),
    ('Transferencia',                         0,      FALSE, TRUE,  2),
    ('Transferencia Hey Banco',               0,      FALSE, TRUE,  3),
    ('Transferencia BBVA',                    0,      FALSE, TRUE,  4),
    ('Tarjeta Mercado Pago',                  0,      TRUE,  TRUE,  5),
    ('Tarjeta Mercado Pago Fiscal Norte',     0,      TRUE,  TRUE,  6),
    ('Tarjeta Mercado Pago No Fiscal Norte',  0,      TRUE,  TRUE,  7),
    ('Tarjeta Hey Banco',                     0,      TRUE,  TRUE,  8),
    ('Tarjeta BBVA',                          0,      TRUE,  TRUE,  9),
    ('Cheque',                                0,      FALSE, TRUE,  10),
    ('Crédito',                               0,      FALSE, TRUE,  11),
    ('Otro',                                  0,      FALSE, TRUE,  12)
ON CONFLICT (nombre) DO NOTHING;

-- 3. Habilitar RLS
ALTER TABLE sys_metodos_pago ENABLE ROW LEVEL SECURITY;

-- 4. Política de acceso (igual que el resto del sistema)
DROP POLICY IF EXISTS "Acceso Total Metodos Pago" ON sys_metodos_pago;
CREATE POLICY "Acceso Total Metodos Pago" ON sys_metodos_pago
    FOR ALL USING (true) WITH CHECK (true);

-- 5. Índices
CREATE INDEX IF NOT EXISTS idx_metodos_pago_activo ON sys_metodos_pago(activo);
CREATE INDEX IF NOT EXISTS idx_metodos_pago_orden  ON sys_metodos_pago(orden);

-- =====================================================
-- VERIFICACIÓN: Ejecuta esto para confirmar que quedó bien
-- SELECT id, nombre, tasa_base, aplica_iva, activo, orden
-- FROM sys_metodos_pago
-- ORDER BY orden;
-- =====================================================
