-- =====================================================
-- MÓDULO POS (PUNTO DE VENTA) - SCHEMA SQL
-- Ejecutar en Supabase SQL Editor
-- NO modifica tablas existentes, solo crea nuevas
-- =====================================================

-- 1. Sesiones de Caja (Aperturas/Cierres)
CREATE TABLE IF NOT EXISTS caja_sesiones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  sucursal TEXT NOT NULL,               -- 'Norte', 'Sur'
  fecha DATE NOT NULL,

  -- Apertura
  fecha_apertura TIMESTAMPTZ,
  fondo_inicial NUMERIC(12,2) DEFAULT 0,
  usuario_apertura TEXT,

  -- Cierre
  fecha_cierre TIMESTAMPTZ,
  efectivo_esperado NUMERIC(12,2),
  efectivo_real NUMERIC(12,2),
  diferencia NUMERIC(12,2),
  fondo_siguiente NUMERIC(12,2),        -- Lo que queda para mañana
  retiro_banco NUMERIC(12,2),           -- Lo que se retira
  usuario_cierre TEXT,
  notas_cierre TEXT,

  -- Estado
  estado TEXT DEFAULT 'ABIERTA' CHECK(estado IN ('ABIERTA', 'CERRADA')),

  -- Evitar duplicados: solo una caja abierta por sucursal por día
  UNIQUE(sucursal, fecha, estado)
);

-- 2. Movimientos de Caja (Entradas/Salidas manuales de efectivo)
CREATE TABLE IF NOT EXISTS caja_movimientos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  sesion_id BIGINT REFERENCES caja_sesiones(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL CHECK(tipo IN ('ENTRADA', 'SALIDA')),
  monto NUMERIC(12,2) NOT NULL,
  concepto TEXT,
  usuario TEXT
);

-- 3. Items de Venta (Detalle de productos vendidos por transacción)
CREATE TABLE IF NOT EXISTS venta_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  transaccion_id UUID NOT NULL,         -- Referencia a transacciones.id
  sesion_caja_id BIGINT REFERENCES caja_sesiones(id),

  producto_id BIGINT REFERENCES productos(id),
  producto_nombre TEXT,                 -- Snapshot del nombre al momento de venta
  producto_sku TEXT,                    -- Snapshot del SKU

  cantidad NUMERIC(10,2) NOT NULL,
  precio_unitario NUMERIC(12,2) NOT NULL,
  precio_tipo TEXT,                     -- 'PUBLICO', 'VENTA2', 'VENTA3', 'MERCADOLIBRE'

  descuento_porcentaje NUMERIC(5,2) DEFAULT 0,
  subtotal NUMERIC(12,2),

  -- Impuestos calculados
  iva_porcentaje NUMERIC(5,2) DEFAULT 0,
  iva_monto NUMERIC(12,2) DEFAULT 0,
  ieps_porcentaje NUMERIC(5,2) DEFAULT 0,
  ieps_monto NUMERIC(12,2) DEFAULT 0,

  total NUMERIC(12,2)
);

-- =====================================================
-- RLS POLICIES
-- =====================================================
ALTER TABLE caja_sesiones ENABLE ROW LEVEL SECURITY;
ALTER TABLE caja_movimientos ENABLE ROW LEVEL SECURITY;
ALTER TABLE venta_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Acceso Total Caja Sesiones" ON caja_sesiones;
DROP POLICY IF EXISTS "Acceso Total Caja Movimientos" ON caja_movimientos;
DROP POLICY IF EXISTS "Acceso Total Venta Items" ON venta_items;

CREATE POLICY "Acceso Total Caja Sesiones" ON caja_sesiones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total Caja Movimientos" ON caja_movimientos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acceso Total Venta Items" ON venta_items FOR ALL USING (true) WITH CHECK (true);

-- =====================================================
-- ÍNDICES PARA RENDIMIENTO
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_caja_sesiones_sucursal ON caja_sesiones(sucursal);
CREATE INDEX IF NOT EXISTS idx_caja_sesiones_fecha ON caja_sesiones(fecha);
CREATE INDEX IF NOT EXISTS idx_caja_sesiones_estado ON caja_sesiones(estado);
CREATE INDEX IF NOT EXISTS idx_caja_movimientos_sesion ON caja_movimientos(sesion_id);
CREATE INDEX IF NOT EXISTS idx_venta_items_transaccion ON venta_items(transaccion_id);
CREATE INDEX IF NOT EXISTS idx_venta_items_sesion ON venta_items(sesion_caja_id);
CREATE INDEX IF NOT EXISTS idx_venta_items_producto ON venta_items(producto_id);
CREATE INDEX IF NOT EXISTS idx_venta_items_fecha ON venta_items(created_at);

-- =====================================================
-- Agregar tipo VENTA a movimientos_stock si no existe
-- =====================================================
ALTER TABLE movimientos_stock
DROP CONSTRAINT IF EXISTS movimientos_stock_tipo_check;

ALTER TABLE movimientos_stock
ADD CONSTRAINT movimientos_stock_tipo_check
CHECK(tipo IN ('ENTRADA', 'SALIDA', 'AJUSTE', 'TRANSFERENCIA_IN', 'TRANSFERENCIA_OUT', 'VENTA', 'DEVOLUCION'));
